%% File for plots of interest
% Created for easier viewing of data found in simulink

%% Rotation of thrusters to desired angle
figure
%figure('Angle')
plot(angle,'LineWidth',1.0)
grid on
xlabel('Time [s]')
ylabel('Angle [Deg]')
legend('Thruster1','Thruster2','Thruster3','Thruster4','Thruster5','Thruster6')

%% Thruster force plot: Desired thrust vs Actual thrust
figure
%figure('Thruster Force')
subplot(3,2,1)
plot(thrust.time,thrust.data(:,1),thrust.time,thrust.data(:,7))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 1')
legend('Desired thrust','Actual thrust')
subplot(3,2,2)
plot(thrust.time,thrust.data(:,2),thrust.time,thrust.data(:,8))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 2')
legend('Desired thrust','Actual thrust')
subplot(3,2,3)
plot(thrust.time,thrust.data(:,3),thrust.time,thrust.data(:,9))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 3')
legend('Desired thrust','Actual thrust')
subplot(3,2,4)
plot(thrust.time,thrust.data(:,4),thrust.time,thrust.data(:,10))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 4')
legend('Desired thrust','Actual thrust')
subplot(3,2,5)
plot(thrust.time,thrust.data(:,5),thrust.time,thrust.data(:,11))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 5')
legend('Desired thrust','Actual thrust')
subplot(3,2,6)
plot(thrust.time,thrust.data(:,6),thrust.time,thrust.data(:,12))
xlabel('time [s]')
ylabel('Thrust [N]')
title('Thruster 6')
legend('Desired thrust','Actual thrust')

%% Shaft speed of each thruster 
figure
%figure('ShaftSpeed')
subplot(3,2,1)
plot(shaftspeedthruster1)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 1')
legend('Desired shaftspeed','Actual shaftspeed')
subplot(3,2,2)
plot(shaftspeedthruster2)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 2')
legend('Desired shaftspeed','Actual shaftspeed')
subplot(3,2,3)
plot(shaftspeedthruster3)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 3')
legend('Desired shaftspeed','Actual shaftspeed')
subplot(3,2,4)
plot(shaftspeedthruster4)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 4')
legend('Desired shaftspeed','Actual shaftspeed')
subplot(3,2,5)
plot(shaftspeedthruster5)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 5')
legend('Desired shaftspeed','Actual shaftspeed')
subplot(3,2,6)
plot(shaftspeedthruster6)
xlabel('time [s]')
ylabel('Shaftspeed [RPM]')
title('Thruster 6')
legend('Desired shaftspeed','Actual shaftspeed')

%% Commanded tau in vs tau out
figure
plot(tcin.time,tcin.data,'--',tcout.time,tcout.data,'LineWidth',1.0)
xlabel('Time [s]')
ylabel('Tau [N;N;Nm]')
legend('SurgeIn','SwayIn','YawIn','SurgeOut','SwayOut','YawOut')